// <auto-generated />
using DesafioDuett.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioDuett.Migrations
{
    [DbContext(typeof(DesafioDuettDbContext))]
    [Migration("20221219014849_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DesafioDuett.Models.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ValueA")
                        .HasColumnType("int");

                    b.Property<int>("ValueB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fruits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Banana",
                            ValueA = 10,
                            ValueB = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Maça",
                            ValueA = 8,
                            ValueB = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Laranja",
                            ValueA = 6,
                            ValueB = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
